### ISSUE TITLE
browser.events.Event callback parameters missing

### ISSUE THREAD

**Issue by ghost** [bomjacob/definitelytyped-firefox-webext-browser#11]
https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/schemas/events.json#44

example method (there are more):

```json
{
  "name": "addListener",
  "type": "function",
  "description": "Registers an event listener <em>callback</em> to an event.",
  "parameters": [
    {
      "name": "callback",
      "type": "function",
      "description": "Called when an event occurs. The parameters of this function depend on the type of event."
    }
  ]
}
```

since the parameter is named `callback` it's ignored but maybe it shouldn't be if the function has no `async`?

this only really affects `browser.runtime.Port` since other things don't use this event definition

**Comment by bomjacob** [comment]
Yeah I indeed do not think that callback should be ignored if the function has no async.
