### ISSUE TITLE
extra parameters for events aren't supported

### ISSUE THREAD

**Issue by epicgirl1998** [bomjacob/definitelytyped-firefox-webext-browser#5]
an example event (from [`toolkit/components/extensions/schemas/web_request.json`](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/schemas/web_request.json#272)):

```json
"extraParameters": [
  {
    "$ref": "RequestFilter",
    "name": "filter",
    "description": "A set of filters that restricts the events that will be sent to this listener."
  },
  {
    "type": "array",
    "optional": true,
    "name": "extraInfoSpec",
    "description": "Array of extra information that should be passed to the listener function.",
    "items": {
      "$ref": "OnBeforeRequestOptions"
    }
  }
]
```

from a quick search it seems like the only events with extra parameters are in that file and [`web_navigation.json`](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/schemas/web_navigation.json)

the parameters are passed after the callback to the `addListener` call but not needed for the other event methods that take the callback as an argument (`removeListener`, `hasListener`)

```typescript
browser.webRequest.onBeforeRequest.addListener(
    () => {},
    {urls: ["<all_urls>"]},
    ["blocking"]
);
```

currently you can only pass in a callback even when an extra parameter is required

---

a solution could be to just generate a new interface for each event that has extra parameters

i thought of suggesting generic `WebExtEventListenerN` interfaces where `N` is the number of extra parameters, but optional extra parameters wouldn't work with it

**Comment by bomjacob** [comment]
I believe #7 should be enough to fix this. Care to take a look?
